version: "3.8"

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build: ./
    restart: on-failure
    env_file:
      - ./.env
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "3000:3000"
    command: ["/entrypoint.sh"]

volumes:
  db-data:
