services:
  - type: web
    name: your-app-name-backend
    env: docker
    plan: free
    docker:
      dockerfile: Dockerfile
    envVars:
      - key: NODE_ENV
        value: production
    healthCheckPath: /health